const USERNAME = 'USERNAME';
const USERPROFILEPICTURE = 'USERPROFILEPICTURE';
const PARENTMOBILE = 'PARENTMOBILE';
const SCHOOLCONTACT = 'SCHOOLCONTACT';

export {USERNAME, USERPROFILEPICTURE, PARENTMOBILE, SCHOOLCONTACT};
